ir/demo/urls.py
from django.conf.urls import url 
 
from . import views 
app_name = "demo"
urlpatterns = [ 
    url(r'^$', views.index, name='index'),
    url(r'^advanced/$', views.advanced_index, name='advanced_index'),
    url(r'^(?P<text>[\w.@+-]*)/(?P<page>[0-9]+)/$', views.search, name='search'),
    url(r'^(?P<page>[0-9]+)/$', views.advanced_search, name='advanced_search'),
    url(r'^(?P<page>[0-9]+)/(?P<title>[\w.@+-]*)/(?P<description>[\w.@+-]*)/(?P<content>[\w.@+-]*)/(?P<date1>[\w.@+-]*)/(?P<date2>[\w.@+-]*)$', views.advanced_search, name='advanced_search'),
]

ir/ir/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('demo/', include('demo.urls')),
]

ir/urls.py
from django.conf.urls import include, url
from django.contrib import admin 
 
urlpatterns = [
    url(r'^demo/', include('demo.urls')),
    url(r'^admin/', admin.site.urls),
]

ir/demo/models.py
from django.db import models

# Create your models here.

ir/demo/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse, QueryDict
from elasticsearch import Elasticsearch
from django.core.paginator import Paginator
from .ResultsProxy import ResultsProxy
from .custom_pagination import custom_pagination
import time
 
def index(request):
    template = loader.get_template('demo/index.html')
    context = {
        
    }
    return HttpResponse(template.render(context, request))

def advanced_index(request):
    template = loader.get_template('demo/advanced_index.html')
    context = {
        
    }
    return HttpResponse(template.render(context, request))

def search(request, text, page):
    size = 10
    text_search = request.GET.get('textsearch','')
    if text_search == '':
        text_search = text
    page1 = request.GET.get('page')
    if page1 == None:
        page1 = page
    es = Elasticsearch([{'host': 'localhost', 'port': 9200}])
    doc = {
        "query": {
            "bool" : {
            "should" : [
                {"match_phrase" : {"title" : text_search}},
                {"match_phrase" : {"description" : text_search}},
                {"match_phrase" : {"content" : text_search}},
                {"match" : {"title" : text_search}},
                {"match" : {"description" : text_search}},
                {"match" : {"content" : text_search}}
            ]
            }
        }
    }
    #create object
    ress = ResultsProxy(es, "vnexpress", doc)
    page1 = int(page1)
    start = (page1 - 1) * size
    end = start + size
    t1 = time.time()
    cnt = ress.__len__()
    sl = slice(start, end, 1)
    t2 = time.time()
    tmp = ress.__getitem__(sl)
    sub_time = round(t2-t1, 4) #tinh thoi gian

    #pagination
    p = custom_pagination(cnt, size)
    xxx = p.gen_page(page1)
    page_obj = p.gen_page_obj(page1)
    for x in tmp:
        x['source'] = x['_source']
    return render(request, 'demo/search.html', {
        'res': tmp,'page_obj': page_obj, 'text': text_search.replace(' ', '+'), 'value': text_search.replace('+',' '),'count':cnt, 'time': sub_time, 'xxx': xxx
    })

def advanced_search(request, page, title = None, description = None, content = None, date1 = None, date2 = None):
    size = 10
    title1 = request.GET.get('title','')
    description1 = request.GET.get('description','')
    content1 = request.GET.get('content','')
    date1_1 = request.GET.get('date1','')
    date2_1 = request.GET.get('date2','')
    
    page1 = request.GET.get('page')
    if page1 == None:
        page1 = page
    if title != None:
        title1 = title
    if description != None:
        description1 = description 
    if content != None:
        content1 = content 
    if date1 != None:
        date1_1 = date1
    if date2 != None:
        date2_1 = date2 
    obj = {"title": title1, "description": description1, "content": content1,"date1": date1_1, "date2": date2_1}
    es = Elasticsearch([{'host': 'localhost', 'port': 9200}])
    #tim kiem theo cac truong title, description, content
    #khi co dau vao khac "" thi moi tim kiem
    must_match = []
    if(title1 != ""):
        obj_title = {"match_phrase" : {"title" : title1}}
        must_match.append(obj_title)
    if(description1 != ""):
        obj_description = {"match_phrase" : {"description" : description1}}
        must_match.append(obj_description)
    if(content1 != ""):
        obj_content = {"match_phrase" : {"content" : content1}}
        must_match.append(obj_content)
    doc = {
        "query": {
            "bool" : {
            "must" : must_match
            }
        }
    }
    #create object
    ress = ResultsProxy(es, "vnexpress", doc)
    page1 = int(page1)
    start = (page1 - 1) * size
    end = start + size
    t1 = time.time()
    sl = {"date1": date1_1, "date2": date2_1, "start": start, "end": end}
    res = ress.__getitembydate__(sl)
    tmp = res["tmp"]
    cnt = res["count"]
    t2 = time.time()
    sub_time = round(t2-t1, 4) #tinh thoi gian

    #pagination
    p = custom_pagination(cnt, size)
    xxx = p.gen_page(page1)
    page_obj = p.gen_page_obj(page1)
    for x in tmp:
        x['source'] = x['_source']
    return render(request, 'demo/advanced_search.html', {
        'res': tmp,'page_obj': page_obj, 'time': sub_time, 'xxx': xxx, "obj":obj,"cnt": cnt
    })

ir/demo/templates/demo/advanced_index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
    <div class="content">
        <div class="logo"><h1>ADVANCED SEARCH</h1></div>
        <div>
            <form action="{% url 'demo:advanced_search' 1%}" method="get">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-2">
                        <span>Tiêu đề</span>
                    </div>
                    <div class="col-md-9">
                        <input class="form-control" type="text" name="title">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        <span>Mô tả</span>
                    </div>
                    <div class="col-md-9">
                        <input class="form-control" type="text" name="description">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        <span>Nội dung</span>
                    </div>
                    <div class="col-md-9">
                        <input class="form-control" type="text" name="content">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        <span>Từ ngày</span>
                    </div>
                    <div class="col-md-4">
                        <input class="form-control" type="date" name="date1">
                    </div>
                    <div class="col-md-2">
                        <span>đến ngày</span>
                    </div>
                    <div class="col-md-4">
                        <input class="form-control" type="date" name="date2">
                    </div>
                </div>
                
                <button type="submit">Tìm kiếm</button>
            </form>
        </div>
        <a href="/demo">quay lại trang tìm kiếm</a>
    </div>
</body>
</html>
<style>
    body{
        font-family: "Times New Roman", Times, serif;
    }
    .content{
        margin: 2%;
    }
    .logo h1{
        font-size: 40px;
    }
    .search input{
        font-size: 16px;
        width: 400px;
        height: 46px;
        border: 1px solid rgb(223, 225, 229);
        line-height: 21px;
        padding-left: 25px;
    }
    .search button{
        height: 51px;
        border: 1px solid rgb(223, 225, 229);
        background: #3578E5;
        cursor: pointer;
        color: white;
        transition: all 0.5s;
    }
    .search button:hover{
        background: black;

    }
</style>

ir/demo/templates/demo/advanced_search.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<div style="margin-left: 5%;">
    <form action="{% url 'demo:advanced_search' 1%}" method="get">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-1">
                <span>Tiêu đề</span>
            </div>
            <div class="col-md-9">
                <input value="{{obj.title}}" class="form-control" type="text" name="title">
            </div>
        </div>
        <div class="row">
            <div class="col-md-1">
                <span>Mô tả</span>
            </div>
            <div class="col-md-9">
                <input value="{{obj.description}}" class="form-control" type="text" name="description">
            </div>
        </div>
        <div class="row">
            <div class="col-md-1">
                <span>Nội dung</span>
            </div>
            <div class="col-md-9">
                <input value="{{obj.content}}" class="form-control" type="text" name="content">
            </div>
        </div>
        <div class="row">
            <div class="col-md-1">
                <span>Từ ngày</span>
            </div>
            <div class="col-md-2">
                <input value="{{obj.date1}}" class="form-control" type="date" name="date1">
            </div>
            <div class="col-md-1">
                <span>đến ngày</span>
            </div>
            <div class="col-md-2">
                <input value="{{obj.date2}}" class="form-control" type="date" name="date2">
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                <button type="submit">Tìm kiếm</button>
            </div>
            <div class="col-md-4">
                <div style="">Tìm được <b>{{cnt}}</b> kết quả sau khoảng <b>{{time}}s</b></div>
            </div>
        </div>
        
    </form>
    
</div>
<div style="margin: 10px; font-size: 16px; margin-left: 30px;">
    <div style="margin-left: 13%;margin-right: 10%;">
        {% for item in res %}
        {% if item.source.ishide == False %}
            <div style="border-bottom: 1px dashed bisque;">
                <a style="font-size: 18px;" href="{{item.source.url}}">
                    {{item.source.title}}
                </a>
                <br>
                <i style="font-size: 12px;">{{item.source.upload_time}}</i>
                <p>
                    {{item.source.description}}
                </p>
                <br>
            </div>
        {%endif%}
        {% endfor %}
    </div>
    
    <div style="text-align: center;" class="pagination">
        {%if page_obj.isPrev%}
            <a href="/demo/{{ page_obj.prev }}">&laquo;</a>
        {%endif%}
        {% for item in xxx %}
            {%if item == page_obj.current%}
                <a class="active">{{item}}</a>
            {%endif%}
            {%if item != page_obj.current%}
                <a href="/demo/{{ item }}/{{obj.title}}/{{obj.description}}/{{obj.content}}/{{obj.date1}}/{{obj.date2}}">{{item}}</a>
            {%endif%}
            
        {% endfor %}
        {%if page_obj.isNext%}
            <a href="/demo/{{ page_obj.next }}">&raquo;</a>
        {%endif%}
        
    </div>
</div>

<style>
    .search input{
        font-size: 16px;
        width: 400px;
        height: 46px;
        border: 1px solid rgb(223, 225, 229);
        line-height: 21px;
        padding-left: 25px;
    }
    .search button{
        height: 51px;
        border: 1px solid rgb(223, 225, 229);
        background: #3578E5;
        cursor: pointer;
        color: white;
        transition: all 0.5s;
    }
    .search button:hover{
        background: black;

    }
    .pagination {
        display: inline-block;
        width: 100%;
    }

    .pagination a {
        color: black;
        /* float: left; */
        padding: 8px 16px;
        text-decoration: none;
    }

    .pagination a.active {
        background-color: #4CAF50;
        color: white;
    }

    .pagination a:hover:not(.active) {background-color: #ddd;}
</style>

ir/demo/templates/demo/index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search</title>
</head>
<body>
    <div class="content">
        <div class="logo"><h1>INFORMATION RETRIEVAL</h1></div>
        <div class="search">
            <form action="{% url 'demo:search' '' 1%}" method="get">
                {% csrf_token %}
                <input type="text" placeholder="Nhập nội dung bạn cần tìm" name="textsearch" required>
                <button type="submit">Tìm kiếm</button>
            </form>
            <a href="./advanced">Tìm kiếm nâng cao</a>
        </div>
    </div>
</body>
</html>
<style>
    body{
        font-family: "Bitstream Vera Sans Mono", Monaco, "Courier New", Courier, monospace;
    }
    .content{
        text-align: center;
        margin-top: 12%;
    }
    .logo h1{
        font-size: 40px;
    }
    .search input{
        font-size: 16px;
        width: 400px;
        height: 46px;
        border: 1px solid rgb(223, 225, 229);
        line-height: 21px;
        padding-left: 25px;
    }
    .search button{
        height: 51px;
        border: 1px solid rgb(223, 225, 229);
        background: #3578E5;
        cursor: pointer;
        color: white;
        transition: all 0.5s;
    }
    .search button:hover{
        background: black;

    }
</style>

ir/demo/templates/demo/search.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<div style="display: flex;">
    <div style="width: 15%;">
        <h1 style="margin-top: 10px;"><a href="/demo">HOME</a></h1>
    </div>
    <div style="width: 85%;" class="search">
        <form action="{% url 'demo:search' '' 1%}" method="get">
            {% csrf_token %}
            <input type="text" value="{{value}}" name="textsearch" required>
            <button type="submit">Tìm kiếm</button>
        </form>
        <div style="margin-left: 16%;">Tìm được <b>{{count}}</b> kết quả sau khoảng <b>{{time}}s</b></div>
    </div>
</div>

<div style="margin: 10px; font-size: 16px; margin-left: 30px;">
    <div style="margin-left: 13%;margin-right: 10%;">
        {% for item in res %}
            <div style="border-bottom: 1px dashed bisque;">
                <a style="font-size: 18px;" href="{{item.source.url}}">
                    {{item.source.title}}
                </a>
                <br>
                <i style="font-size: 12px;">{{item.source.upload_time}}</i>
                <p>
                    {{item.source.description}}
                </p>
                <br>
            </div>
        {% endfor %}
    </div>
    
    <div style="text-align: center;" class="pagination">
        {%if page_obj.isPrev%}
            <a href="/demo/{{text}}/{{ page_obj.prev }}">&laquo;</a>
        {%endif%}
        {% for item in xxx %}
            {%if item == page_obj.current%}
                <a class="active">{{item}}</a>
            {%endif%}
            {%if item != page_obj.current%}
                <a href="/demo/{{text}}/{{ item }}">{{item}}</a>
            {%endif%}
            
        {% endfor %}
        {%if page_obj.isNext%}
            <a href="/demo/{{text}}/{{ page_obj.next }}">&raquo;</a>
        {%endif%}
        
    </div>
</div>

<style>
    .search input{
        font-size: 16px;
        width: 400px;
        height: 46px;
        border: 1px solid rgb(223, 225, 229);
        line-height: 21px;
        padding-left: 25px;
    }
    .search button{
        height: 51px;
        border: 1px solid rgb(223, 225, 229);
        background: #3578E5;
        cursor: pointer;
        color: white;
        transition: all 0.5s;
    }
    .search button:hover{
        background: black;

    }
    .pagination {
        display: inline-block;
        width: 100%;
    }

    .pagination a {
        color: black;
        /* float: left; */
        padding: 8px 16px;
        text-decoration: none;
    }

    .pagination a.active {
        background-color: #4CAF50;
        color: white;
    }

    .pagination a:hover:not(.active) {background-color: #ddd;}
</style>